server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

weixin:
  config:
    originalid: gh_04f2f06c4f26
    token: b8b6
    app-id: wx841f4dbbe7f85fd6
    app-secret: a3d9094b6a18706cb34b84bfe492d97e
    template_id: sNEhaKiF2OuOjzfJOQSqtpearO22nejVK1OEPPXu35w

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:13306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000158650978
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCo6rqv4yH7L7v4zMaT0ov6/pkjrOKeJOxq3j6nJxahaQvsYQyjj1ZR8SEs5bN0RbSmQFzkcwU+e2wCjibMovUBP9akSjsMuOkGAhKQduQSTVlTnMhVTuE4Qhm05w5VecccOCzn+ehmEog1aKEG3Cwr8orOlBcU/wlzPKpgQUJ+RF05VMOeuDq9YIaJTg+Z4COgSCzlhYr9e0xD8EqBq+BdwDhoaWXfQjXtLLbFbkVByio6vmRC0lXTMpNFUJbCsHcrk/qeN4jj/Llb8rfCLQfK16mbX/SuW1pSH/leYqAyw1ApPVgCyOrf90nMrbqRrxw7udeBWCrMmAkgAsy7B8xvAgMBAAECggEAM95ADRpVqOfzdGaM439XdG8RXx8LRzxXTEmKO5GJJW84NhFm7CJrgyXj5gFypVVyL0q8O3oGNjV36SD1UQkI6qVLp48Tqshs5Wdlg+6+AdC2iTIvYeKizb+eXSpGAIEwXr3xLBpU/mLaaGwEZjLdbXFApkZbABuAL16FgqEHZfXe2nyWMeI9iioiPpsEydPpVFjj8GcVG4oWzdoTPnJroYFy6OumK8YdXA+u80ltFhelmBvempRIxrjflwxChzB9Ivkwm46JjRCG8NZnayQrvtzwW43TqX7PQpgN71ZBDcSgwA65HGcOvW0JLNQn8+K75d6Bp2k1MYZr+cm1hGOMgQKBgQDy26rl+PvyZOz50AV/y49Dvh0GHuBmw/8wLCxdKD4i/PL9zMVGXMU0JUHBD6M09Jseb8PKgpTf5xzEb9FgLYuYaD8oSTjEvTo4uQMbwOqedE24bAVMvkq+AtCW7NI7GAQr2bUBAjHqs4gu1REJSicbxFiHgNFKjVJn7S6DHnfUfwKBgQCyDr+vxN8LR2jByXLav3/nDg28kEMRXSpB86BLRoeDA7hcaoFHXBEeC4eyWiU57mBodOohYL52CV+psHR030uW0bO5/+1ZgKVyhitLLj8ePqpQiUpH+mn0RXJ89lHASgxAL8mPFpHfS8gewoXI1qKd/0MX2h+fo9Me1GrDC9VQEQKBgQDVxqnL3/0fpNm5GPUORkhpEDuKPLm5nEPQysGOizMPJ2xaHtt0kYsB2N3lrPc0UTEOfMFzTLjx0wXOoMNEjzL3SKR3uOSgwhUzAyEKWCnuq2ASu/t6T3OJiP7GK9bvL7fURcKADceU2s5As0tYyw5b8d0gAjO5FWd5lh3AS5ydzwKBgQCFJEwndZHG0E2/4g+VDG7qafLRlhngaQbJLBAnWYTI7cY0rJsgrfJKwhpkvc1qRRon4YyVCs9AWgADVeOu5K2UCBhZM8raCz0rprHG1Lzzs64M7KvzqIcD1c4nLNSycWw5rsIL0bef/f2VKqV5KS2N8SrNMhhFee3K9tEiKb4G0QKBgA0yvrTuqENNwpH7WL4KixlRSgeDe+xuWsVlkS6jElRkmfBNhQqz6nYG5W1Os5oqmPJPw0uO3+enZQRuLSGEUHBpArTr/07NA50C9eO12V6/xxSBkeybzTf6Cn+b9DeEtCqZ+GPz46gkrzrAsGW9ZlWLFxretIOh5g4mkGtvPKwL
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgZlrFidGakck3q6mcbv1qPV8XsbDdGnRk2Eb8RWEf3rFKWMM/rh3CnomdZFM1I8256qb7ZAvOrt0wKwzKz9PGNnFhMeBzL28PvIGuN3pCneOqGudaAVnHSyZNwQDS0t5upCw5cXwR9exC/4Zx7u0l/+bh5Ldh1VSvgl2yU7JO/bNr0xQIgzw6vGpAJiqewN6fZY15CUHDIipBuUJqxBsQ00HfKZUcLmjRBdJ0zQ3pMxA6lteXnGP3w9ZBl0DTh3myvFdCWT/lwrQehCVJ0WZAiI0OB/JVNIR6hZxg8JvaVBjEo+L8oLS0pwaZI0ku3XS/4i+Q0bRiKI3B8TodZEOpwIDAQAB
  notify_url: http://gwj-mall.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml